name: testApp
configs:
  Debug: debug
  Release: release
options:
  deploymentTarget:
    iOS: 10.0
  developmentLanguage: ja
settings:
  base:
    SWIFT_VERSION: 5.0

schemes:
  testApp:
    build:
      targets:
        testApp: all
        testAppTests: [test]
        testAppUITests: [test]
    run: 
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive: 
      config: Debug

  testApp_DEMO:
    build:
      targets:
        testApp_DEMO: all
    run: 
      config: Debug
    test:
      config: Debug
    profile: 
      config: Release
    analyze:
      config: Debug
    archive: 
      config: Release

  testApp_PRD:
    build:
      targets:
        testApp_PRD: all
    run: 
      config: Debug
    test:
      config: Debug
    profile: 
      config: Release
    analyze:
      config: Debug
    archive: 
      config: Release

targets:
  testApp:
    type: application
    platform: iOS
    sources: testApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: test.testApp.stg
        INFOPLIST_FILE: testApp/plist/testApp_STG.plist
        MARKETING_VERSION: 1.0.1
        CURRENT_PROJECT_VERSION: 10
        GCC_PREPROCESSOR_DEFINITIONS:
          - "$(inherited)"
          - STG=1
        OTHER_SWIFT_FLAGS: -DSTG
    # dependencies:
    #   - target: testFw.framework
    #     embed: false
    scheme:
      testTargets:
        - testAppTests
        - testAppUITests

  testApp_DEMO:
    type: application
    platform: iOS
    sources: testApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: test.testApp.demo
        INFOPLIST_FILE: testApp/plist/testApp_DEMO.plist
        MARKETING_VERSION: 1.0.2
        CURRENT_PROJECT_VERSION: 2
        GCC_PREPROCESSOR_DEFINITIONS:
          - "$(inherited)"
          - DEMO=1
        OTHER_SWIFT_FLAGS: -DDEMO
    # dependencies:
    #   - target: testFw
    #     embed: false

  testApp_PRD:
    type: application
    platform: iOS
    sources: testApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: test.testApp.prd
        INFOPLIST_FILE: testApp/plist/testApp_PRD.plist
        MARKETING_VERSION: 1.0.3
        CURRENT_PROJECT_VERSION: 3
        GCC_PREPROCESSOR_DEFINITIONS:
          - "$(inherited)"
          - PRD=1
        OTHER_SWIFT_FLAGS: -DPRD
    # dependencies:
    #   - target: testFw
    #     embed: false

  testAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: testAppTests
    settings:
      base:
        INFOPLIST_FILE: testAppTests/Info.plist
    dependencies:
      - target: testApp

  testAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: testAppUITests
    settings:
      base:
        INFOPLIST_FILE: testAppUITests/Info.plist
    dependencies:
      - target: testApp
