name: testApp
options:
  bundleIdPrefix: test.testApp
  deploymentTarget:
    iOS: 13.0
  developmentLanguage: ja

targets:
  testApp:
    type: application
    platform: iOS
    sources: 
      - testApp
    settings:
      base:
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: testApp/Info.plist
        DEVELOPMENT_LANGUAGE: ja
    scheme:
      testTargets:
        - testAppTests
        - testAppUITests

  testAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: testAppTests
    settings:
      base:
        INFOPLIST_FILE: testAppTests/Info.plist
    dependencies:
      - target: testApp

  testAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: testAppUITests
    settings:
      base:
        INFOPLIST_FILE: testAppUITests/Info.plist
    dependencies:
      - target: testApp
