# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'iOS.xcworkspace'

project 'testApp/testApp.xcodeproj'
project 'testFw/testFw.xcodeproj'

abstract_target 'iOS' do

    target 'testApp' do
    	project 'testApp/testApp.xcodeproj'
      use_frameworks!

      pod 'Swinject'
      pod 'R.swift'
      pod 'SwiftLint'
    end

    target 'testFw' do
        project 'testFw/testFw.xcodeproj'
        use_frameworks!

        pod 'Swinject'
        pod 'R.swift'
        pod 'SwiftLint'
    end

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
      end
    end

end

