# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'iOS.xcworkspace'

pod 'Swinject'
pod 'R.swift'
pod 'SwiftLint'

abstract_target 'iOS' do

    target 'testApp' do
    	project 'testApp/testApp.xcodeproj'
      use_frameworks!
    end

    target 'testFw' do
        project 'testFw/testFw.xcodeproj'
        use_frameworks!
    end

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
      end
    end

end

